---
- hosts: "{{ target_hosts }}"
  remote_user: "{{ ansible_user }}"
  any_errors_fatal: true

  roles:
    - role: ping
      tags: [ ping ]
    - role: prerequisites
      tags: [ prerequisites ]
    - role: docker
      tags: [ docker ]