---
- hosts: "{{ target_hosts }}"
  remote_user: "{{ ansible_user }}"
  any_errors_fatal: true

  roles:
    - role: test
      tags: [ test ]
    - role: ping
      tags: [ ping ]
    - role: docker
      tags: [ docker ]
    - role: prerequisites
      tags: [ prerequisites ]
    - role: infrastructure
      tags: [ infrastructure ]
