---
# tasks file for roles/infrastructure
- name: Prerequisites, Docker
  block:
    - name: Run role 'prerequisites'
      ansible.builtin.include_role:
        name: prerequisites

    - name: Run role 'docker'
      ansible.builtin.include_role:
        name: docker