---
# tasks file for roles/infrastructure
- name: Prerequisites, Docker
  block:
    - name: Run role 'prerequisites'
      ansible.builtin.include_role:
        name: prerequisites
#      tags: [ never ]

    - name: Run role 'docker'
      ansible.builtin.include_role:
        name: docker
  rescue:
    - name: Run role 'prerequisites' - task 'cleanup'
      ansible.builtin.include_role:
        name: prerequisites
        tasks_from: cleanup

    - name: Run role 'docker' - task 'cleanup_docker'
      ansible.builtin.include_role:
        name: docker
        tasks_from: cleanup_docker