---
# vars file for roles/docker
terraform:
  vsphere_version: "2.2.0"
  required_version: "0.13"
  module:
    version_tf_template:
      mode: "0644"
      src: "versions.tf.j2"
      dest: "pocVSphere/tf/versions.tf"

project:
  name: terraform
  definition:
    version: "3.9"
    services:
      vault:
        image: "vault"
        cap_add: "IPC_LOCK"
        vault_api_port: 8201
        restart: "on-failure:5"
        container_name: "vault"
        vault_console_port: 8200
        secret_username: "vaultadmin"
        secret_password: "vaultadmin"
        user:
          id: 100
          group: 1000
        healthcheck:
          retries: 1
          interval: 10s
          timeout: 10s
          start_period: 1s
      s3:
        mode: "0644"
        s3_api_port: 9000
        container_name: s3
        storage_class: "EC:0"
        s3_console_port: 9001
        restart: "on-failure:5"
        access_key: "minioadmin"
        secret_key: "minioadmin"
        image: "quay.io/minio/minio"
        healthcheck:
          retries: 1
          interval: 10s
          timeout: 10s
          start_period: 1s
        s3_bucket:
          name: "demo"
          state: present
          versioning: true
          encryption: "none"
          file: "policy.json"
          validate_certs: true
          requester_pays: false
          permission: "private"
          endpoint_url: "https://www"
          tags:
            value: "demo bucket"
        user:
          id: 1000
          group: 1000
