---
# vars file for roles/docker
terraform:
  vsphere_version: "2.2.0"
  required_version: "0.13"
  module:
    version_tf_template:
      mode: "0644"
      src: "versions.tf.j2"
      dest: "pocVSphere/tf/versions.tf"

project:
  name: terraform
  definition:
    version: "3.9"
    services:
      cert:
        mode: "0755"
        size: 4096
        force: false
        recurse: true
        dir: "demoDir"
        format: "auto"
        cipher: "auto"
        acme_version: 2
        state: directory
        terms_agreed: yes
        csr: "public.csr"
        crt: "public.crt"
        key: "private.key"
        country_name: "DK"
        remaining_days: 365
        challenge: "http-01"
        provider: "selfsigned"
        passphrase: "passphrase"
        common_name: "sample.com"
        chain_dest: "intermediate.crt"
        fullchain_dest: "fullchain.crt"
        organization_name: "ORGANIZATION"
        email_address: "demo@mydomain.com"
        challenge_dir: ".well-known/acme-challenge"
        acme_directory: "https://acme-v02.api.letsencrypt.org/directory"
        subject_alt_name:
          - "IP:0.0.0.0"
          - "DNS:sample.com"
          - "DNS:local.sample.org"
      vault:
        image: "vault"
        api_port: 8201
        vault_port: 8200
        dir: "vaultDemoDir"
        cap_add: "IPC_LOCK"
        restart: "on-failure:5"
        container_name: "vault"
        secret_username: "vaultadmin"
        secret_password: "vaultadmin"
        user:
          id: 100
          group: 1000
        healthcheck:
          retries: 1
          interval: 10s
          timeout: 10s
          start_period: 1s
        dirs:
          logs: "logs"
          file: "file"
          certs: "certs"
          config: "config"
      s3:
        dir: "s3DemoDir"
        vault_port: 9001
        console_port: 9000
        container_name: s3
        restart: "on-failure:5"
        access_key: "minioadmin"
        secret_key: "minioadmin"
        image: "quay.io/minio/minio"
        healthcheck:
          retries: 1
          interval: 10s
          timeout: 10s
          start_period: 1s
        s3_bucket:
          name: "demo"
          state: present
          versioning: true
          encryption: "none"
          file: "policy.json"
          validate_certs: true
          requester_pays: false
          permission: "private"
          endpoint_url: "https://www"
          tags:
            value: "demo bucket"
        user:
          id: 1000
          group: 1000
        dirs:
          data: "data"
          certs: "certs"
