---
# tasks file for roles/ping
- name: Example from an Ansible Playbook
  ansible.builtin.ping:
  delegate_to: localhost

- name: Induce an exception to see what happens
  ansible.builtin.ping:
    data: crash
  delegate_to: localhost