---
# tasks file for roles/terraform init
- debug:
    msg: "{{ item }}"
  loop:
    - "{{ docker.project.definition.services.vault.secret_username }}"
    - "{{ docker.project.definition.services.vault.secret_password }}"

- name: Vault that requires authentication via LDAP
  debug:
    msg: "{{ lookup('hashi_vault', 'creds=s3/username:value auth_method={{ terraform.auth_method }} username={{ docker.project.definition.services.vault.secret_username }} password={{ docker.project.definition.services.vault.secret_password }} url=https://{{ inventory_hostname }}:{{ docker.project.definition.services.s3.s3_api_port }}')}}"

#- name: Define the backend configuration at init
#  community.general.terraform:
#    state: "{{ terraform.state }}"
#    force_init: "{{ terraform.force_init }}"
#    project_path: "{{ terraform.project_path }}"
#    backend_config:
#      access_key: ""
#      secret_key: ""