local:
  hosts:
    localhost:
  vars:
    uid: 1000
    gid: 1000
    user: 'tinyos'
    group: 'tinyos'

demo:
  hosts:
    localhost:

sampleWithParameters:
  hosts:
    localhost:
  vars:
    uid: 9999
    gid: 9999
    user: 'myTechnicalUser'
    group: 'myTechnicalGroup'

