local:
  hosts:
    localhost:

demo:
  hosts:
    localhost:

sampleWithParameters:
  hosts:
    localhost:
  vars:
    uid: 9999
    gid: 9999
    user: 'myTechnicalUser'
    group: 'myTechnicalGroup'

