---
# tasks file for roles/docker cleanup
- name: Remove sensitive file(s) (certificates)
  ansible.builtin.file:
    path: /etc/foo.txt
    state: absent
  with_items:
    - "{{ role_path }}/files/{{ project.definition.services.cert.key }}"
    - "{{ role_path }}/files/{{ project.definition.services.cert.crt }}"
    - "{{ role_path }}/files/{{ project.definition.services.cert.csr }}"
