- name: Template a file to vault config dir
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
  with_items:
    - { src: "vault_config.hcl.j2", dest: "{{ ansible_env.HOME }}/{{ project.definition.services.cert.dir }}/{{ project.definition.services.vault.dir }}/{{ project.definition.services.vault.dirs.config }}/vault_config.hcl" }