---
# tasks file for roles/docker docker_compose
- community.docker.docker_compose:
    project_name: "{{ project.name }}"
    definition:
      version: "{{ project.definition.version }}"
      services:
        vault:
          image: "{{ project.definition.services.vault.image }}"
          restart: "{{ project.definition.services.vault.restart }}"
          container_name: "{{ project.definition.services.vault.container_name }}"
#          user: "{{ project.definition.services.vault.user.id }}:{{ project.definition.services.vault.user.group }}"
          ports:
            - "{{ project.definition.services.vault.ui_port }}:{{ project.definition.services.vault.ui_port }}"
          cap_add:
            - "{{ project.definition.services.vault.cap_add }}"
        s3:
          image: "{{ project.definition.services.s3.image }}"
          restart: "{{ project.definition.services.s3.restart }}"
          container_name: "{{ project.definition.services.s3.container_name }}"
          command: "server /data --console-address ':{{ project.definition.services.s3.ui_port }}'"
          user: "{{ project.definition.services.s3.user.id }}:{{ project.definition.services.s3.user.group }}"
          healthcheck:
            test: [ "CMD", "curl", "-If", "--cacert", ".minio/certs/{{ project.definition.services.s3.cert.crt }}", "https://localhost:{{ project.definition.services.s3.ui_port }}" ]
            timeout: "{{ project.definition.services.s3.healthcheck.timeout }}"
            retries: "{{ project.definition.services.s3.healthcheck.retries }}"
            interval: "{{ project.definition.services.s3.healthcheck.interval }}"
            start_period: "{{ project.definition.services.s3.healthcheck.start_period }}"
          environment:
            - "MINIO_ROOT_USER={{ project.definition.services.s3.access_key }}"
            - "MINIO_ROOT_PASSWORD={{ project.definition.services.s3.secret_key }}"
            - "MINIO_CERT_PASSWD={{ project.definition.services.s3.cert.passphrase }}"
          volumes:
            - "{{ ansible_env.HOME }}/{{ project.definition.services.s3.dirs.dir }}/{{ project.definition.services.s3.dirs.data }}:/data"
            - "{{ ansible_env.HOME }}/{{ project.definition.services.s3.dirs.dir }}/{{ project.definition.services.s3.dirs.certs }}:/.minio/certs"
          ports:
            - "{{ project.definition.services.s3.ui_port }}:{{ project.definition.services.s3.ui_port }}"
            - "{{ project.definition.services.s3.console_port }}:{{ project.definition.services.s3.console_port }}"
          depends_on:
            - vault
  register: output

- ansible.builtin.assert:
    that:
      - "output.services.s3.{{ project.definition.services.s3.container_name }}.state.running"
      - "output.services.vault.{{ project.definition.services.vault.container_name }}.state.running"
