---
# tasks file for roles/docker
- name: Import variables from prerequisites role
  ansible.builtin.include_vars:
    file: "{{ role_path }}/../prerequisites/vars/main.yml"
    name: prerequisites

- name: Config for Vault
  ansible.builtin.include_tasks:
    file: config.yaml

- name: Docker compose task
  ansible.builtin.include_tasks:
    file: docker_compose.yaml

#    - name: Create S3 Bucket
#      ansible.builtin.include_tasks:
#        file: s3.yaml

#    - name: Prepare Terraform Version file
#      ansible.builtin.include_tasks:
#        file: version.yaml
#  always:
#    - name: Remove Sensitive data (CRT)
#      ansible.builtin.include_tasks:
#        file: cleanup.yaml