---
# tasks file for roles/docker
- name: Complete block of container processes
  block:
    - name: Import variables from prerequisites role
      ansible.builtin.include_vars:
        file: "{{ role_path }}/../prerequisites/vars/main.yml"
        name: prerequisites

    - name: Config for Vault
      ansible.builtin.include_tasks:
        file: config.yml

    - name: Docker compose task
      ansible.builtin.include_tasks:
        file: docker_compose.yml

    - name: Docker compose task
      ansible.builtin.include_tasks:
        file: docker_container.yml
