---
# tasks file for roles/docker prerequisites
- name: Create a directories for minio data and certs if they do not exist
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/{{ item.value }}"
    mode: "{{ project.definition.services.s3.dirs.mode }}"
    state: "{{ project.definition.services.s3.dirs.state }}"
    recurse: "{{ project.definition.services.s3.dirs.recurse }}"
  with_dict: "{{ project.definition.services.s3.dirs }}"