---
# tasks file for roles/docker prerequisites
- name: Create a directory for minio data if it does not exist
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/{{ minio.minio_data_dir }}"
    state: directory
    mode: '0755'